export const CHANGE_PORT = "CHANGE_PORT";
export const CHANGE_ADDRESS = "CHANGE_ADDRESS";
export const SET_DATA_BEGIN = "SET_DATA_BEGIN";
export const SET_DATA_SUCCESS = "SET_DATA_SUCCESS";
export const SET_DATA_ERROR = "SET_DATA_ERROR";
export const SET_CURRENT_ANIMATION = "SET_CURRENT_ANIMATION";
